[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Ensure shared volume for Redis (optional if using Railway Redis plugin)
numReplicas = 1

[env]
PORT = "8000" 